services:
  obsidian-vps-publish:
    build:
      context: .
      dockerfile: Dockerfile

    image: obsidian-vps-publish:dev

    user: '0:0'

    env_file:
      - .env.dev

    volumes:
      - type: volume
        source: content
        target: /content
        volume:
          nocopy: false
      - type: volume
        source: assets
        target: /assets
        volume:
          nocopy: false

volumes:
  content:
    driver: local
  assets:
    driver: local
